# /home/althof/.config/tmuxinator/bbaw.yml

name: bbaw
root: ~/

# Optional tmux socket
# socket_name: foo

# Runs before everything. Use it to start daemons etc.
# pre: sudo /etc/rc.d/mysqld start

# Project hooks
# Runs on project start, always
# on_project_start: command
# Run on project start, the first time
# on_project_first_start: command
# Run on project start, after the first time
# on_project_restart: command
# Run on project exit ( detaching from tmux session )
# on_project_exit: command
# Run on project stop
# on_project_stop: command

# Runs in each window and pane before window/pane specific commands. Useful for setting up interpreter versions.
# pre_window: rbenv shell 2.0.0-p247

# Pass command line options to tmux. Useful for specifying a different tmux.conf.
# tmux_options: -f ~/.tmux.mac.conf

# Change the command to call tmux.  This can be used by derivatives/wrappers like byobu.
# tmux_command: byobu

# Specifies (by name or index) which window will be selected on project startup. If not set, the first window is used.
# startup_window: editor

# Specifies (by index) which pane of the specified window will be selected on project startup. If not set, the first pane is used.
# startup_pane: 1

# Controls whether the tmux session should be attached to automatically. Defaults to true.
# attach: false

# Runs after everything. Use it to attach to tmux with custom options etc.
# post: tmux -CC attach -t bbaw
name: bbaw

windows:
  - home:
      layout: main-vertical
      panes:
        - ls:
          - cd ~/Homestead
          - vagrant up
        - monitoring:
          - htop
        - discusage:
          - ranger
  - thrakien: 
      layout: main-vertical
      panes:
        - vim:
          - cd /var/www/html/thrakien
          - vim
        - shell:
          - cd /var/www/html/thrakien
          - git pull
  - td:
      panes:
        - td:
           - ssh td 
           - cd /opt/data/projekte/thrakien
           - ls -lah
  - thrakien-laravel: 
      layout: main-vertical
      panes:
        - vim:
          - cd /var/www/html/thrakien-thrakien-laravel
          - vim
        - shell:
          - cd /var/www/html/thrakien-laravel
          - git pull
  - thrakien-web: 
      layout: main-vertical
      panes:
        - vim:
          - cd /var/www/html/thrakien-web-laravel
          - vim
        - shell:
          - cd /var/www/html/thrakien-web-laravel
          - git pull
  - twd:
      panes: 
        - twd:
          - ssh twd 
          - cd /opt/projects/corpus-nummorum/src
          - ls -lah
