#=============================================================================
# basic.toml --- basic configuration example for SpaceVim
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "hybrid"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # update automatically
    automatic_update = 1
    # font
    guifont = "SauceCodePro Nerd Font Mono, Light:h11"
#
# STATUSLINE
# 
    statusline_separator = "arrow"
    statusline_inactive_separator = "bar"
    # Set SpaceVim buffer index type
    # 0: 1 ➛ ➊
    # 1: 1 ➛ ➀
    # 2: 1 ➛ ⓵
    # 3: 1 ➛ ¹
    # 4: 1 ➛ 1
    buffer_index_type = 3
    windows_index_type = 2
    enable_tabline_filetype_icon = false
    statusline_unicode_symbols = true
    # Enable/Disable show mode on statusline
    enable_statusline_mode = true
# options for statusline
    # 'winnr' window number
    # 'syntax checking'
    # 'filename' file name
    # 'fileformat' file format
    # 'major mode'
    # 'minor mode lighters'
    # 'cursorpos' cursor position
    # 'percentage' content range
    # 'date' date
    # 'time' time
    # 'whitespace' line number with trailing space at the end
    # 'battery status' battery status
    # 'input method' input method
    # 'search status' search index
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts

    # left sections of statusline
    statusline_left_sections = [
       'winnr',
       'major mode',
       'filename',
       'fileformat',
       'minor mode lighters',
       'version control info',
       'search status'
    ]
    # right sections of statusline
    statusline_right_sections = [
       'cursorpos',
       'percentage',
       'input method',
       'date',
       'time'
    ]

#
# VIM
#
    # Enable vim compatible mode, avoid changing origin vim key bindings
    vimcompatible = true
#
# FILEMANAGER
# 
    # Replacing filemanager
    filemanager = 'nerdtree'
#
# AUTOCOMPLETE
#
    spacevim_autocomplete_method = "coc"
#
# LAYERS
#
[[layers]]
    name = "core#statusline"

[[layers]]
    name = "core#tabline"

# Enable autocomplete layers
[[layers]]
    name = 'autocomplete'
    auto-completion-return-key-behavior = "complete"
    auto-completion-tab-key-behavior = "cycle"

[[layers]]
    name = 'lang#php'

[[layers]]
    name = 'lang#sh'

[[layers]]
    name = 'lang#css'

[[layers]]
    name = 'lang#html'

[[layers]]
    name = 'lang#javascript'

[[layers]]
  name = "lsp"
  filetypes = [
    "php"
  ]

[[layers]]
    name = 'shell'
    default_position = 'bottom'
    default_height = 30

[[layers]]
    name = 'colorscheme'

[[layers]]
    name = 'ctrlp'

[[layers]]
    name = "denite"

[[layers]]
    name = 'git'

[[layers]]
    name = 'ui'

[[layers]]
    name = 'default'

[[layers]]
    name = 'tags'

[[layers]]
  name = "checkers"
  show_cursor_error = false

[[layers]]
  name = "markdown"

[[custom_plugins]]
    name = 'vimwiki/vimwiki'
    merged = false
